#+TITLE: LFlame: Initial Conditions Specification
#+AUTHOR: Anup Zope

* Uniform Initial Conditions

Specified using ~initialConditions~ options list. For example:

#+BEGIN_SRC
initialConditions: <...>
#+END_SRC

The options list must contain:
1. Specifiction of two out of the three thermodynamic variables:
   (~density~ [kg/m^3], ~pressure~ [N/m^2], ~temperature~ [K]).
2. Specification of one out of the two velocity variables: (~velocity~
   [m/s], ~Mach~ [unitless]). These variable values must be either a
   single number (with or without units) or must be a list.
   1. In case it is a single number (e.g. ~velocity=20 m/s~ or
      ~Mach=6.5~), it is treated as the $x$-component of the vector.
   2. In case it is a list, it can contain 1 to 4 components. When the
      list has 1 to 3 components (e.g. ~velocity=[200 m/s, 100 m/s]~
      or ~Mach=[0.5]~), they are treated as $x$, $y$, and $z$
      components of the vector. Missing components are set to zero.
   3. If the list has 4 components, the first three components are for
      specifying direction of the vector and the fourth component is
      the magnitude of the vector. The direction is normalized before
      multiplying with the magnitude. For example: ~velocity=[1, 1,
      0.0, 650 m/s]~ is specification of velocity of magnitude 650
      [m/s] acting parallel to $xy$-plane at 45$^\circ$ angle of
      attack.
3. Specification of one out of the two species fractions variables
   (not required for single-species case): (~massFractions~
   [unitless], ~molarFractions~ [unitless]). The order of the
   fractions must be the same as the species order in the mixture
   ~xml~ file. If the last species fraction is omitted, it is
   automatically computed to make the sum of all the species fractions
   equal to 1.0.

* Region-based Initial Conditions

Specified using ~initialConditionRegions~ options list. For example:
#+BEGIN_SRC
initialConditionRegions: <
  defaultState=state(...),
  stateA=state(...)
  stateB=state(...),
  regionR1=regionFunction(...),
  regionR2=regionFunction(...),
  regionR3=regionFunction(...),
  setStateForRegionR1=A,
  setStateForRegionR2=B,
  setStateForRegionR3=default
>
#+END_SRC

1. Option ~defaultState~ is mandatory. This state is used for cells
   that do not fall in any of the specified regions. This state can
   also be explcitly specified for a region using the state name as
   ~default~, e.g. ~setStateForRegionR3=default~.
2. The ~state()~ function must contain:
   1. Specifiction of two out of three thermodynamic variables
      (optional unit specification): (~density~ [kg/m^3], ~pressure~
      [N/m^2], ~temperature~ [K]),
   2. Specification of one out of two velocity variables: (~velocity~
      [m/s], ~Mach~ [unitless]).
   3. Specification of one out of two species fractions variables (not
      required for single-species case): (~massFractions~ [unitless],
      ~molarFractions~ [unitless]). The order of the fractions must be
      the same as the species order in the mixture ~xml~ file. If the
      last species fraction is omitted, it is automatically computed
      to make the sum of all the species fractions equal to 1.0.
3. ~regionFunction()~ can be one of:
   1. ~leftPlane()~: All the cells with cell centers on the left side
      of the plane specified by,
      1. ~point=[x, y, z]~: (x [m], y [m], z [m])-coordinates of a
         point on the plane,
      2. ~normal=[nx, ny, nz]~: (x [m], y [m], z [m])-coordinates of
         the normal of the plane (need not be normalized).
      The left side of the plane is the region of space on the
      opposite side of the plane's normal.
   2. ~rightPlane()~: All the cells with cell centers to the right
      side of the plane specified by,
      1. ~point=[x, y, z]~: (x [m], y [m], z [m])-coordinates of a
         point on the plane,
      2. ~normal=[nx, ny, nz]~: (x [m], y [m], z [m])-coordinates of
         the normal of the plane (need not be normalized).
      The right side of the plane is the region of space in the
      direction of the plane's normal.
   3. ~sphere()~: All the cells with cell centers inside the sphere
      specified by,
      1. ~center=[x, y, z]~: (x [m], y [m], z [m])-coordinates of the
         center of the sphere,
      2. ~radius=r~: radius of the sphere.
   4. ~box()~: All the cells with cell centers inside the
      coordinate-axes aligned box specified by,
      1. ~corner1=[x, y, z]~: (x [m], y [m], z [m])-coordinates of the
         first corner of the box,
      2. ~corner2=[x, y, z]~: (x [m], y [m], z [m])-coordinates of the
         second corner of the box.
      Any two opposite corners of the box can be chosen for the
      specification. For example, ~corner1.x~ need not be less that
      ~corner2.x~. Same for ~y~, and ~z~.
   5. ~convexPolyhedron()~: All the cells with cell centers on the
      left side of each plane specified by ~(pointX=[x, y, z],
      normalX=[nz, ny, nz])~ pairs, where ~X~ represents an identifier
      for the pair.

* Taylor-Green Vortex (TGV) Initial Conditions

Specified using ~initialConditionsTGV~ options list. For example,

#+BEGIN_SRC
initialConditionsTGV: <
  referencePosition=[x0, y0, z0],
  referenceLength=[Lx, Ly, Lz],
  referenceMode=[Kx, Ky, Kz],
  referencePressure=P0,
  referenceDensity=r0,
  referenceVelocity=U0
>
#+END_SRC

Required options are:
1. ~referencePosition=[...]~: Specifies the origin of the Taylor-Green
   vortex.
2. ~referenceLength=[...]~: Specifies the reference length in each
   coordinate direction.
3. ~referenceMode=[...]~: Specifies the spatial modes $(K_x, K_y,
   K_z)$ in each coordinate direction.
4. ~referencePressure~: Specifies the reference pressure ($P_0$).
5. One of (~referenceDensity~, ~referenceTemperature~): Specifies the
   reference density ($\rho_0$) or reference temperature ($T_0$). When
   ~referenceDensity~ is specifies, the initial mixture density is
   constant throughpout the domain and reference temperature is
   calculated from the equation of state. When ~referenceTemperature~
   is specified, the initial temperature is constant throughout the
   domain and reference density is calculated from the equation of
   state.
6. One of (~referenceVelocity~, ~referenceMach~): Specifies the
   reference velocity ($U_0$) or reference Mach number ($M_0$). When
   ~referenceMach~ is specified, the reference speed of sound (based
   on reference temperature $T_0$) is calculate from the equation of
   state, which is then used to calculate the reference velocity.

The pressure and velocity at a spatial point $(x, y, z)$ are
calculated from:

\begin{equation}
P = P_0 +
0.0625 r_0 U_0^2 \left( \cos\left(\frac{2 K_x (x-x0)}{Lx}\right) + \cos\left(\frac{2 K_y (y-y0)}{Ly}\right) \right) \times
\left( 2 + \cos\left(\frac{2 k_x (z - z_0)}{L_z}\right) \right)
\end{equation}

\begin{equation}
U = \begin{bmatrix}
U_0 \sin\left(\frac{K_x (x - x_0)}{L_x}\right) \cos\left(\frac{K_y (y - y_0)}{L_y}\right) \cos\left(\frac{K_y (y - y_0)}{L_y}\right) \\
-U_0 \cos\left(\frac{K_x (x - x_0)}{L_x}\right) \sin\left(\frac{K_y (y - y_0)}{L_y}\right) \cos\left(\frac{K_y (y - y_0)}{L_y}\right) \\
0.0
\end{bmatrix}
\end{equation}
